services:
  app:
    build: .
    restart: unless-stopped
    container_name: sheethappens_server
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongodb:8.0.4
    restart: unless-stopped
    container_name: sheethappens_db
    env_file:
      - .env
    expose:
      - "27017"
